Repository googleapis/nodejs-dialogflow-cx, pull requests merged in 2020-12, with the labels that each got.

#42 chore: generate GAPIC metadata JSON file
  src/v3/gapic_metadata.json
  src/v3beta1/gapic_metadata.json
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#41 docs: improved instructions for samples and tests
  README.md
  linkinator.config.json
  samples/detect-intent-audio.js
  samples/detect-intent-streaming.js
  samples/detect-intent-text.js
  samples/list-intents.js
  samples/quickstart.js
  samples/resources/book_a_room.wav
  samples/test/detect-intent-audio.test.js
  samples/test/detect-intent-text.test.js
  samples/test/list-intents.test.js
Labels: api: dialogflow, cla: yes

#43 docs: update READMEs
  README.md
  linkinator.config.json
  samples/README.md
  synth.metadata
Labels: api: dialogflow, cla: yes, context: none

#47 docs: add instructions for authenticating for system tests
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full
