Repository googleapis/nodejs-dialogflow-cx, pull requests merged in 2020-11, with the labels that each got.

#26 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full

#27 fix: do not modify options object, use defaultScopes
  package.json
  protos/google/cloud/dialogflow/cx/v3beta1/agent.proto
  protos/google/cloud/dialogflow/cx/v3beta1/audio_config.proto
  protos/google/cloud/dialogflow/cx/v3beta1/entity_type.proto
  protos/google/cloud/dialogflow/cx/v3beta1/flow.proto
  protos/google/cloud/dialogflow/cx/v3beta1/gcs.proto
  protos/google/cloud/dialogflow/cx/v3beta1/intent.proto
  protos/google/cloud/dialogflow/cx/v3beta1/ivr.proto
  protos/google/cloud/dialogflow/cx/v3beta1/page.proto
  protos/google/cloud/dialogflow/cx/v3beta1/response_message.proto
  protos/google/cloud/dialogflow/cx/v3beta1/session.proto
  protos/google/cloud/dialogflow/cx/v3beta1/session_entity_type.proto
  protos/google/cloud/dialogflow/cx/v3beta1/webhook.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/index.ts
  src/v3beta1/agents_client.ts
  src/v3beta1/agents_proto_list.json
  src/v3beta1/entity_types_client.ts
  src/v3beta1/entity_types_proto_list.json
  src/v3beta1/environments_client.ts
  src/v3beta1/environments_proto_list.json
  src/v3beta1/flows_client.ts
  src/v3beta1/flows_proto_list.json
  src/v3beta1/intents_client.ts
  src/v3beta1/intents_proto_list.json
  src/v3beta1/pages_client.ts
  src/v3beta1/pages_proto_list.json
  src/v3beta1/session_entity_types_client.ts
  src/v3beta1/session_entity_types_proto_list.json
  src/v3beta1/sessions_client.ts
  src/v3beta1/sessions_proto_list.json
  src/v3beta1/transition_route_groups_client.ts
  src/v3beta1/transition_route_groups_proto_list.json
  src/v3beta1/versions_client.ts
  src/v3beta1/versions_proto_list.json
  src/v3beta1/webhooks_client.ts
  src/v3beta1/webhooks_proto_list.json
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: dialogflow, automerge, cla: yes

#30 feat: adds event to MessageType
  protos/google/cloud/dialogflow/cx/v3beta1/session.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: dialogflow, cla: yes, context: none

#33 build: additional annotation in protos.json
  protos/protos.json
  synth.metadata
Labels: api: dialogflow, cla: yes, context: none

#11 docs: update quickstart to reflect actual use case
  .github/CODEOWNERS
  README.md
  samples/package.json
  samples/quickstart.js
  samples/test/quickstart.js
  synth.metadata
Labels: api: dialogflow, cla: yes

#37 chore: address linting issue
  src/v3/transition_route_groups_client.ts
  synth.metadata
Labels: api: dialogflow, cla: yes, context: none

#38 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: dialogflow, automerge, cla: yes, context: full
